//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication14.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WalletBCS153114
    {
        public int WalletId { get; set; }
        public string WalletName_ { get; set; }
        public string Description_ { get; set; }
        public Nullable<int> Amount { get; set; }
    }
}
